import java.util.Scanner;
import java.util.Random;

public class Lab1Q2 {
	public static void main(String[] args) {
		Scanner input = new Scanner(System.in);

		//Generate a number
		Random rdm = new Random();
		int guess = rdm.nextInt(6);
		int good_guess;

		//Ask for input
		System.out.println("An integer has been generated by the computer. (0-5)");
			;
		int counter = 0;
		do {
			System.out.print("Guess it: ");
			good_guess = input.nextInt();

			if (good_guess != guess) {
				System.out.println("*Wrong guess! Try again*");
				System.out.println();
				counter++;
			} else {
				System.out.println("*You got it!*");
				break;
			}
		} while(counter<5);

		if (counter==5) System.out.println("Nice try :)");

	}
}